---
title: "Consulting"
description: |
  \> I welcome consulting requests from private and public organizations, political parties, NGO's, and other organizations.
output: distill::distill_article
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, results='asis'}
library(metathis)

meta() %>%
  meta_social(
    title = "jvieroe: Consulting",
    description = "Code, Plots, and All Things R",
    url = "https://jvieroe.github.io",
    image = "https://raw.githubusercontent.com/jvieroe/jvieroe.github.io/main/images/sl_plot.png",
    image_alt = "Serial development",
    og_type = "website",
    og_author = "Jeppe Vierø",
    twitter_card_type = "summary_large_image",
    twitter_creator = "@jvieroe"
  )
```


Services include:

* Data visualization
* Multivariate regression analysis
* Causal inference
* Geo-spatial data analysis and visualization
* Data wrangling

<br>

<!-- Services include: -->

<!-- <ul class="fa-ul"> -->
<!--   <li><i class="fa-li fa fa-chart-bar"></i>Data visualization</li> -->
<!--   <li><i class="fa-li fa fa-check-square"></i>Multivariate regression analysis</li> -->
<!--   <li><i class="fa-li fa fa-square"></i>Causal inference</li> -->
<!--   <li><i class="fa-li fas fa-tools"></i>Data wrangling</li> -->
<!--   <li><i class="fa-li fa fa-square"></i>Geo-spatial data analysis and visualization</li> -->
<!-- </ul> -->

<!-- <br> -->

Want to make a request or hear more about how I can help? Don't hesitate to [get in touch](mailto:jvieroe@gmail.com)!